version: '3.8'

services:
  db : 
    image: postgres:16
    container_name: movies-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies

    ports:
      - "3333:3333"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d
  
  api:
    build: .
    container_name: filmes-api
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: filmes
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
- db_data:

