### Criar review
POST http://localhost:3334/movies/3/reviews
Content-Type: application/json

{
    "reviewer_name": "João",
    "rating": 9,
    "comment": "Filme de merda!"
}

###

###  Listar reviews de um filme
GET http://localhost:3334/movies/3/reviews

###  Deletar review
DELETE http://localhost:3334/movies/3/reviews/3