### Criar review
POST http://localhost:3334/movies/2/reviews
Content-Type: application/json

{
    "reviewer_name": "João",
    "rating": 9,
    "comment": "Filme de merda!"
}

###

###  Listar reviews de um filme
GET http://localhost:3334/movies/MOVIE_ID_HERE

###  Deletar review
DELETE http://localhost:3334/movies/MOVIE_ID_HERE/reviews/REVIEW_ID_HERE