POST https://first-node-project-bgs8.onrender.com/videos
Content-Type: application/json

{
    "title" : "video node",
    "description" : "esse é o primeiro video",
    "duration" : 180
}

###

GET https://first-node-project-bgs8.onrender.com/videos


###

PUT https://first-node-project-bgs8.onrender.com/videos/1c92a66d-6f65-42f0-bc7d-08d7ad0185b9
Content-Type: application/json

{
    "title" : "video 69",
    "description" : "esse é o primeiro video",
    "duration" : 180
}


###

DELETE https://first-node-project-bgs8.onrender.com/videos/f8c6712a-8d46-4299-a0ec-19602f5ef302


