### 1️⃣ Criar vídeo
POST http://localhost:3334/movies
Content-Type: application/json

{
    "title": "video node 2",
    "description": "esse é o segundo video",
    "duration": 180
}

###

### 2️⃣ Listar vídeos
GET http://localhost:3334/movies

###

### 3️⃣ Atualizar vídeo
# Substitua SEU_VIDEO_ID pelo id retornado ao criar ou listar vídeos
PUT http://localhost:3334/movies/60104350-2758-43f3-9565-27b8e01d8df1
Content-Type: application/json

{
    "title": "video 69",
    "description": "atualizando o vídeo",
    "duration": 180
}

###

### 4️⃣ Deletar vídeo
# Substitua SEU_VIDEO_ID pelo id que deseja deletar
DELETE http://localhost:3334/movies/60104350-2758-43f3-9565-27b8e01d8df1
